theme = "manual"

[editor]
mouse=false
auto-pairs = false
text-width = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
# newline = "·"
tabpad = "→" # Tabs will look like "→···" (depending on tab width)

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[keys.insert]
"C-d" = [
  ":insert-output echo -n \"=== $(date -d '3 hours ago' +%Y-%m-%d)\n\n/ Wer:\n/ Was:\n/ Gelernt:\n/ Bereut:\n/ Körper:\n/ Gedanken:\n/ Lustig:\n/ Idee:\n/ Morgen:\n/ TLDR:\"",
  "ensure_selections_forward",
  "flip_selections",
  "move_line_down",
  "move_line_down",
  "insert_at_line_end"
]

[keys.normal]
"x" = ["extend_to_line_bounds", "select_mode"]
# AI Append
"C-ret" = [
  "select_all",
  ":pipe curl http://localhost:4051/text_generation --data-binary @-",
  "ensure_selections_forward",
  "collapse_selection",
]

# "C-ret" = [
#   "extend_to_line_bounds",
#   "trim_selections", # Remove \n
#   "ensure_selections_forward",
#   "flip_selections",
#   "select_mode",
#   "goto_file_start",
#   ":pipe curl http://localhost:4051/text_generation --data-binary @-",
#   "ensure_selections_forward",
#   "normal_mode",
#   "collapse_selection",
# ]

# TTS R=Rede mit mir
"C-r" = [
  "save_selection",
  "extend_to_line_bounds",
  "trim_selections", # Remove \n
  "ensure_selections_forward",
  "select_mode",
  "goto_file_end",
  ":pipe-to spd-say -C && spd-say -e",
  "normal_mode",
  "jump_backward",
  "jump_backward",
]

"C-R" = [
  ":run-shell-command spd-say -C",
]

# Calc
"C-k" = [
  # "move_char_right", # Select whole set of equations
  # "goto_prev_paragraph",
  # "goto_next_paragraph",
  # "trim_selections", # Remove empty lines
  "extend_to_line_bounds", # Include \n
  # Select line without last equal sign, then pipe it into both echo and kalker
  ":pipe sd ' ?[=≈].*\\n?\\z' '' | { x=$(cat); echo \"$x ≈\" \"$(kalker -p 16 \"$x\" 2>&1)\"; }",
  ":append-output echo -n ≈", # Move cursor back to last equal sign
  "search_selection",
  "delete_selection",
  "search_prev",
]

# Typst shortcuts
[keys.normal."C-t"]
# Compile and open
"o" = ["save_selection", "select_all", ":pipe-to typst compile - /home/timo/.typst.pdf", ":run-shell-command firefox /home/timo/.typst.pdf", "jump_backward"]
# Compile
"c" = ["save_selection", "select_all", ":pipe-to typst compile - /home/timo/.typst.pdf", "jump_backward"]
